export const servicesLineOne = {
  id: "1",
  cards: [
    {
      id: "syrianUntold",
      title: "Syria Untold",
      cardIcon: "/Assests/syrianUntold/syrianUntold=1.webp",
      imgLink: "/stories/syrianUntold",
      images: [
        "/Assests/syrianUntold/syrianUntold=1.webp",
        "/Assests/syrianUntold/syrianUntold=2.webp",
        "/Assests/syrianUntold/syrianUntold=3.webp",
        "/Assests/syrianUntold/syrianUntold=4.webp",
      ],
      discription:
        "Syria untold is an independent and non-profit outlet to tell Syrian stories that are otherwise pushed to the margins. We are a space for high-quality writing by Syrian women and men involved in the cultural, civil, environmental and creative spheres. SyriaUntold believes in the importance of feminism, LGBTIQ rights, gender and the environment, and dedicates much of its work to support those who have been pushed to the margins of Syrian society for raising their voices on these topics. ",
    },
    {
      id: "jeem",
      title: "Jeem",
      cardIcon: "/Assests/jeem/jeem=1.webp",
      imgLink: "/stories/jeem",
      images: [
        "/Assests/jeem/jeem=1.webp",
        "/Assests/jeem/jeem=2.webp",
        "/Assests/jeem/jeem=3.webp",
        "/Assests/jeem/jeem=4.webp",
        "/Assests/jeem/jeem=5.webp",
        "/Assests/jeem/jeem=6.webp",
        "/Assests/jeem/jeem=7.webp",
        "/Assests/jeem/jeem=8.webp",
      ],
      discription:
        " Jeem is a website which produces knowledge as well as critical and cultural content about gender, sex and sexuality that challenges and transcends the prevalent discourse of the mainstream media.",
    },
    {
      id: "syrianHumming",
      cardIcon: "/Assests/syrianHumming/syrianHumming=1.webp",
      title: "Syrian Humming",
      imgLink: "/stories/syrianHumming",
      images: [
        "/Assests/syrianHumming/syrianHumming=1.webp",
        "/Assests/syrianHumming/syrianHumming=2.webp",
        "/Assests/syrianHumming/syrianHumming=3.webp",
        "/Assests/syrianHumming/syrianHumming=4.webp",
      ],
      discription:
        "Syrian Humming Hums are never just about songs.They are always more about stories, memories, feelings of you and me. In partnership with arthereistalbul, SERG, and sonADA, and with the generous support by the University of Aberdeen and the Aberdeen City Council (Creative Funding) storytelling.",
    },
    {
      id: "syrianfeministlobby",
      cardIcon: "/Assests/feministLobby/feministLobby=1.webp",
      title: "Syrian Feminist Lobby",
      imgLink: "/stories/syrianfeministlobby",
      images: [
        "/Assests/feministLobby/feministLobby=1.webp",
        "/Assests/feministLobby/feministLobby=2.webp",
        "/Assests/feministLobby/feministLobby=3.webp",
        "/Assests/feministLobby/feministLobby=4.webp",
        "/Assests/feministLobby/feministLobby=5.webp",
        "/Assests/feministLobby/feministLobby=6.webp",
        "/Assests/feministLobby/feministLobby=7.webp",
        "/Assests/feministLobby/feministLobby=8.webp",
        "/Assests/feministLobby/feministLobby=9.webp",
        "/Assests/feministLobby/feministLobby=10.webp",
        "/Assests/feministLobby/feministLobby=11.webp",
        "/Assests/feministLobby/feministLobby=12.webp",
      ],
      discription:
        "لوبي سياسي مستقل غير حزبي يناهض كل اشكال الاستبداد ويؤمن بالديمقراطية والمدنية والتعددية، وبمبدأ المواطنة المتساوية، والمساوة الجندرية، وحقوق الانسان والعدالة الاجتماعية، وبالنضال السلمي كوسيلة للتغيير",
    },
    {
      id: "rainbowFish",
      cardIcon: "/Assests/rainbowFish/rainbowFish=1.webp",
      title: "Rainbow Fish",
      imgLink: "/stories/rainbowFish",
      images: [
        "/Assests/rainbowFish/rainbowFish=1.webp",
        "/Assests/rainbowFish/rainbowFish=2.webp",
        "/Assests/rainbowFish/rainbowFish=3.webp",
        "/Assests/rainbowFish/rainbowFish=4.webp",
        "/Assests/rainbowFish/rainbowFish=5.webp",
        "/Assests/rainbowFish/rainbowFish=6.webp",
        "/Assests/rainbowFish/rainbowFish=7.webp",
        "/Assests/rainbowFish/rainbowFish=8.webp",
        "/Assests/rainbowFish/rainbowFish=9.webp",
        "/Assests/rainbowFish/rainbowFish=10.webp",
        "/Assests/rainbowFish/rainbowFish=11.webp",
        "/Assests/rainbowFish/rainbowFish=12.webp",
        "/Assests/rainbowFish/rainbowFish=13.webp",
        "/Assests/rainbowFish/rainbowFish=14.webp",
        "/Assests/rainbowFish/rainbowFish=15.webp",
        "/Assests/rainbowFish/rainbowFish=16.webp",
        "/Assests/rainbowFish/rainbowFish=17.webp",
        "/Assests/rainbowFish/rainbowFish=18.webp",
        "/Assests/rainbowFish/rainbowFish=19.webp",
        "/Assests/rainbowFish/rainbowFish=20.webp",
        "/Assests/rainbowFish/rainbowFish=21.webp",
        "/Assests/rainbowFish/rainbowFish=22.webp",
        "/Assests/rainbowFish/rainbowFish=23.webp",
      ],
      discription:
        "Syrian Humming Hums are never just about songs.They are always more about stories, memories, feelings of you and me. In partnership with arthereistalbul, SERG, and sonADA, and with the generous support by the University of Aberdeen and the Aberdeen City Council (Creative Funding) storytelling.",
    },
    {
      id: "oralMemory",
      cardIcon: "/Assests/oralMemory/oralMemory=1.webp",
      title: "Oral Memory",
      imgLink: "/stories/oralMemory",
      images: [
        "/Assests/oralMemory/oralMemory=1.webp",
        "/Assests/oralMemory/oralMemory=2.webp",
        "/Assests/oralMemory/oralMemory=3.webp",
      ],
      discription:
        "So I'm not kept in the shadows Oral Memory. This book is a Syrian Women Survivors of detention.",
    },
    {
      id: "hamsa",
      cardIcon: "/Assests/hamsa/hamsa=1.webp",
      title: "Hamsa ",
      imgLink: "/stories/hamsa",
      images: [
        "/Assests/hamsa/hamsa=1.webp",
        "/Assests/hamsa/hamsa=2.webp",
        "/Assests/hamsa/hamsa=3.webp",
      ],
      discription:
        "So I'm not kept in the shadows Oral Memory. This book is a Syrian Women Survivors of detention.",
    },
  ],
};
